# Generated by Django 5.2.7 on 2026-03-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefakt',
            fields=[
            ],
            options={
                'verbose_name': 'Artefakt',
                'verbose_name_plural': 'Artefaktlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.artefakt',),
        ),
        migrations.CreateModel(
            name='TarixiyObida',
            fields=[
            ],
            options={
                'verbose_name': 'Tarixiy obida',
                'verbose_name_plural': 'Tarixiy obidalar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.tarixiyobida',),
        ),
    ]
