# Generated by Django 5.2.7 on 2026-03-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restoran',
            fields=[
            ],
            options={
                'verbose_name': 'Restoran',
                'verbose_name_plural': 'Restoranlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.restoran',),
        ),
        migrations.CreateModel(
            name='Taom',
            fields=[
            ],
            options={
                'verbose_name': 'Taom',
                'verbose_name_plural': 'Taomlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.taom',),
        ),
    ]
