# Generated by Django 5.2.7 on 2026-03-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transportlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.transport',),
        ),
        migrations.CreateModel(
            name='TransportTur',
            fields=[
            ],
            options={
                'verbose_name': 'Transport turi',
                'verbose_name_plural': 'Transport turlari',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.transporttur',),
        ),
    ]
