# Generated by Django 5.2.7 on 2026-03-25 12:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('tavsif', models.TextField(blank=True, null=True)),
                ('davr', models.CharField(blank=True, choices=[('ilk_tosh_devor', 'Ilk Tosh Devr'), ('jemisl_jamoasi', 'Jemisl Jamoasi'), ('qadimgi_yunon', 'Qadimgi Yunon'), ('sak', 'Sak'), ('part', 'Part'), ('sogdiana', 'Sogdiana'), ('xitoy', 'Xitoy'), ('arab', 'Arab'), ('mo_gol', "Mo'g'il"), ('temuriylar', 'Temuriylar'), ('shaxrizoda', 'Shahrizoda')], max_length=30, null=True)),
                ('yoshi', models.PositiveIntegerField(blank=True, help_text='Yoshi yil bilan', null=True)),
                ('material', models.CharField(blank=True, help_text='Material: metall, loy, tosh, va h.k.', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gids/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('language_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='languages/')),
            ],
        ),
        migrations.CreateModel(
            name='Mehmonxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('kunlar', models.CharField(blank=True, help_text='Ish kunlari: dushanba,seshanba,chorshanba,payshanba,juma,shanba,yakshanba', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('kunlar', models.CharField(blank=True, help_text='Ish kunlari: dushanba,seshanba,chorshanba,payshanba,juma,shanba,yakshanba', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Taom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('tavsif', models.TextField(blank=True, null=True)),
                ('narx', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TarixiyObida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/tarixiy_obidalar/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_poster', models.ImageField(blank=True, null=True, upload_to='videos/posters/')),
                ('video_type', models.CharField(choices=[('standard', 'Oddiy video'), ('360', '360 video')], default='standard', max_length=20)),
                ('video_projection', models.CharField(blank=True, choices=[('equirectangular', 'Equirectangular'), ('cubemap', 'Cubemap'), ('fisheye', 'Fisheye')], max_length=30, null=True)),
                ('stereo_mode', models.CharField(choices=[('mono', 'Mono'), ('left_right', 'Left-Right'), ('top_bottom', 'Top-Bottom')], default='mono', max_length=20)),
                ('vr_ready', models.BooleanField(default=False)),
                ('video_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('kunlar', models.CharField(blank=True, help_text='Ish kunlari: dushanba,seshanba,chorshanba,payshanba,juma,shanba,yakshanba', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportTur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='viloyatlar/')),
            ],
        ),
        migrations.CreateModel(
            name='Xususiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(blank=True, choices=[('viloyat', 'Viloyat'), ('restoran', 'Restoran'), ('mehmonxona', 'Mehmonxona'), ('transport', 'Transport'), ('gid', 'Gid'), ('tarixiy_obida', 'Tarixiy obida')], max_length=30)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'core'), ('model__in', ['viloyat', 'restoran', 'mehmonxona', 'transport', 'gid', 'tarixiyobida'])), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
