# Generated by Django 5.2.7 on 2026-03-25 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gid',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gid_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artefakt',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='artefaktlar', to='core.image'),
        ),
        migrations.AddField(
            model_name='gid',
            name='language_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gidlar', to='core.language'),
        ),
        migrations.AddField(
            model_name='mehmonxona',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='mehmonxonalar', to='core.image'),
        ),
        migrations.AddField(
            model_name='mehmonxona',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mehmonxonalar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restoran',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='restoranlar', to='core.image'),
        ),
        migrations.AddField(
            model_name='restoran',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoranlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taom',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='taomlar', to='core.image'),
        ),
        migrations.AddField(
            model_name='taom',
            name='restoran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taomlar', to='core.restoran'),
        ),
        migrations.AddField(
            model_name='tarixiyobida',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='tarixiy_obidalar', to='core.image'),
        ),
        migrations.AddField(
            model_name='artefakt',
            name='tarixiy_obida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artefaktlar', to='core.tarixiyobida'),
        ),
        migrations.AddField(
            model_name='transport',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportlar', to='core.image'),
        ),
        migrations.AddField(
            model_name='transport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transport',
            name='transport_turi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportlar', to='core.transporttur'),
        ),
        migrations.AddField(
            model_name='transport',
            name='viloyat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportlar', to='core.viloyat'),
        ),
        migrations.AddField(
            model_name='tarixiyobida',
            name='viloyat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarixiy_obidalar', to='core.viloyat'),
        ),
        migrations.AddField(
            model_name='restoran',
            name='viloyat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoranlar', to='core.viloyat'),
        ),
        migrations.AddField(
            model_name='mehmonxona',
            name='viloyat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mehmonxonalar', to='core.viloyat'),
        ),
        migrations.AddField(
            model_name='gid',
            name='viloyat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gidlar', to='core.viloyat'),
        ),
        migrations.AddField(
            model_name='comment',
            name='viloyat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoped_comments', to='core.viloyat'),
        ),
        migrations.AddField(
            model_name='transport',
            name='xususiyat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportlar', to='core.xususiyat'),
        ),
        migrations.AddField(
            model_name='restoran',
            name='xususiyat',
            field=models.ManyToManyField(blank=True, related_name='restoranlar', to='core.xususiyat'),
        ),
        migrations.AddField(
            model_name='mehmonxona',
            name='xususiyat',
            field=models.ManyToManyField(blank=True, related_name='mehmonxonalar', to='core.xususiyat'),
        ),
    ]
