# Generated by Django 5.2.7 on 2026-03-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarixiyobida',
            name='stereo_mode',
            field=models.CharField(choices=[('mono', 'Mono'), ('left_right', 'Left-Right'), ('top_bottom', 'Top-Bottom')], default='mono', max_length=20),
        ),
        migrations.AddField(
            model_name='tarixiyobida',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/tarixiy_obidalar/'),
        ),
        migrations.AddField(
            model_name='tarixiyobida',
            name='video_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarixiyobida',
            name='video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='videos/posters/'),
        ),
        migrations.AddField(
            model_name='tarixiyobida',
            name='video_projection',
            field=models.CharField(blank=True, choices=[('equirectangular', 'Equirectangular'), ('cubemap', 'Cubemap'), ('fisheye', 'Fisheye')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tarixiyobida',
            name='video_type',
            field=models.CharField(choices=[('standard', 'Oddiy video'), ('360', '360 video')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='tarixiyobida',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarixiyobida',
            name='vr_ready',
            field=models.BooleanField(default=False),
        ),
    ]
