# Generated by Django 5.2.7 on 2026-03-18 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_tarixiyobida_stereo_mode_tarixiyobida_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='gid',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='mehmonxona',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='restoran',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tarixiy_obida',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='transport',
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'core'), ('model__in', ['viloyat', 'restoran', 'mehmonxona', 'transport', 'gid', 'tarixiyobida'])), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='target_type',
            field=models.CharField(blank=True, choices=[('viloyat', 'Viloyat'), ('restoran', 'Restoran'), ('mehmonxona', 'Mehmonxona'), ('transport', 'Transport'), ('gid', 'Gid'), ('tarixiy_obida', 'Tarixiy obida')], max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='viloyat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoped_comments', to='core.viloyat'),
        ),
    ]
