# Generated by Django 5.2.7 on 2026-03-25 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gid_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('tavsif', models.TextField(blank=True, null=True)),
                ('davr', models.CharField(blank=True, choices=[('ilk_tosh_devor', 'Ilk Tosh Devr'), ('jemisl_jamoasi', 'Jemisl Jamoasi'), ('qadimgi_yunon', 'Qadimgi Yunon'), ('sak', 'Sak'), ('part', 'Part'), ('sogdiana', 'Sogdiana'), ('xitoy', 'Xitoy'), ('arab', 'Arab'), ('mo_gol', "Mo'g'il"), ('temuriylar', 'Temuriylar'), ('shaxrizoda', 'Shahrizoda')], max_length=30, null=True)),
                ('yoshi', models.PositiveIntegerField(blank=True, help_text='Yoshi yil bilan', null=True)),
                ('material', models.CharField(blank=True, help_text='Material: metall, loy, tosh, va h.k.', max_length=100, null=True)),
                ('images', models.ManyToManyField(blank=True, related_name='artefaktlar', to='core.image')),
                ('tarixiy_obida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artefaktlar', to='core.tarixiyobida')),
            ],
        ),
    ]
