# Generated by Django 5.2.7 on 2026-03-25 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_artefakt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gid',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='gid',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='gid',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='gid',
            name='telegram',
        ),
        migrations.CreateModel(
            name='Taom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('tavsif', models.TextField(blank=True, null=True)),
                ('narx', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('images', models.ManyToManyField(blank=True, related_name='taomlar', to='core.image')),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taomlar', to='core.restoran')),
            ],
        ),
    ]
