# Generated by Django 5.2.7 on 2026-03-25 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_remove_gid_bio_remove_gid_experience_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaftaJadvali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('kun', models.CharField(choices=[('dushanba', 'Dushanba'), ('seshanba', 'Seshanba'), ('chorshanba', 'Chorshanba'), ('payshanba', 'Payshanba'), ('juma', 'Juma'), ('shanba', 'Shanba'), ('yakshanba', 'Yakshanba')], max_length=20)),
                ('ochilish_vaqti', models.TimeField(blank=True, null=True)),
                ('yopilish_vaqti', models.TimeField(blank=True, null=True)),
                ('yopiq', models.BooleanField(default=False, help_text="Agar true bo'lsa, bu kuni yopiq")),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'core'), ('model__in', ['restoran', 'mehmonxona', 'tarixiyobida'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['kun'],
            },
        ),
    ]
