# Generated by Django 5.2.7 on 2026-03-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_haftajadvali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haftajadvali',
            name='kun',
            field=models.CharField(blank=True, choices=[('dushanba', 'Dushanba'), ('seshanba', 'Seshanba'), ('chorshanba', 'Chorshanba'), ('payshanba', 'Payshanba'), ('juma', 'Juma'), ('shanba', 'Shanba'), ('yakshanba', 'Yakshanba')], max_length=20),
        ),
        migrations.AlterField(
            model_name='haftajadvali',
            name='yopiq',
            field=models.BooleanField(blank=True, default=False, help_text="Agar true bo'lsa, bu kuni yopiq"),
        ),
    ]
