# Generated by Django 5.2.7 on 2026-03-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_haftajadvali_kun_alter_haftajadvali_yopiq'),
    ]

    operations = [
        migrations.AddField(
            model_name='mehmonxona',
            name='kunlar',
            field=models.CharField(blank=True, help_text='Ish kunlari: dushanba,seshanba,chorshanba,payshanba,juma,shanba,yakshanba', max_length=100),
        ),
        migrations.AddField(
            model_name='restoran',
            name='kunlar',
            field=models.CharField(blank=True, help_text='Ish kunlari: dushanba,seshanba,chorshanba,payshanba,juma,shanba,yakshanba', max_length=100),
        ),
        migrations.DeleteModel(
            name='HaftaJadvali',
        ),
    ]
