# Generated by Django 5.2.7 on 2026-03-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mehmonxona_kunlar_restoran_kunlar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarixiyobida',
            name='kunlar',
            field=models.CharField(blank=True, help_text='Ish kunlari: dushanba,seshanba,chorshanba,payshanba,juma,shanba,yakshanba', max_length=100),
        ),
    ]
