# Generated by Django 5.2.7 on 2026-03-25 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tarixiyobida_kunlar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mehmonxona',
            name='date',
        ),
        migrations.RemoveField(
            model_name='restoran',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tarixiyobida',
            name='date',
        ),
    ]
