# Generated by Django 5.2.7 on 2026-03-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gid',
            fields=[
            ],
            options={
                'verbose_name': 'Gid',
                'verbose_name_plural': 'Gidlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.gid',),
        ),
    ]
