# Generated by Django 5.2.7 on 2026-03-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mehmonxona',
            fields=[
            ],
            options={
                'verbose_name': 'Mehmonxona',
                'verbose_name_plural': 'Mehmonxonalar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.mehmonxona',),
        ),
    ]
